version: '3.8'

services:
  bingo_app:
    extra_hosts:
        - "host.docker.internal:host-gateway" # needed for xdebug
    volumes:
      - .:/var/www
    build:
      dockerfile: ./Dockerfile
      args:
        - ENVIRONMENT
    ports:
       - "80:80"
    env_file:
      - .env
