version: '3.8'

services:
  bingo_app:
    extra_hosts:
        - "host.docker.internal:host-gateway" # needed for xdebug
    volumes:
      - .:/var/www
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT
    ports:
       - "80:80"
    env_file:
      - .env

  queue_worker:
    depends_on:
      - bingo_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT
    command: php artisan queue:work
    volumes:
      - .:/var/www
    env_file:
      - .env
